### ISSUE TITLE
Which OTS Storage Service could be used?

### ISSUE THREAD

**Issue by diversemix** [libero/shared-services-experiment#3]
Using an off the shelf service for storage would appear like a good solution. Let's do some research and choose a candidate.

## Tasks

Review options
- [x] MinIO: emulate S3 interface by running inside a container (or more containers if in a distributed setting)
- [x] OpenStack Swift
- [x] Ceph via K8S+Rook: object storage but still exposes proprietary interfaces (S3, Swift); more difficult to run outside of a cloud

Prepare a demo of MinIO through docker-compose. Some task left with a question mark, to be confirmed if they are in scope.

- [x] Upload a file
- [x] Download a file
- [x] Obtain a link to a file accessible outside of containers (from the host, represents the public)
- [x] Store arbitrary key-value pairs as [object tags](https://docs.aws.amazon.com/AmazonS3/latest/dev/object-tagging.html)
- [x] Read file-specific [metadata](https://stackoverflow.com/questions/19100858/how-do-you-change-the-mime-on-amazon-s3): MIME type, size, updated timestamp
- [x] Access control: bucket can be made [public](https://havecamerawilltravel.com/photographer/how-allow-public-access-amazon-bucket/) so that all links are permanently accessible
- [x] Access control: private bucket can still produce a [shareable link](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/s3-presigned-urls.html) to access a single file that does not require authentication
- [ ] Query by folder?
- [ ] Query by tag?
- [ ] Events related to file creation?

**Comment by giorgiosironi** [comment]
A task that will come up later is how to integrate with the OTS Configuration Service (of course it depends highly on what it is).

**Comment by diversemix** [comment]
@GiancarloFusiello / @giorgiosironi ... what needs to be done to close this off?

**Comment by giorgiosironi** [comment]
Remaining checklist items are postponed, as they are not in the scope of the node.js equivalent.
