### ISSUE TITLE
Deploy node.js Storage Service on a public cloud

### ISSUE THREAD

**Issue by giorgiosironi** [libero/shared-services-experiment#9]
Deployment: how do we deploy reviewer/this $service in a way that we replicate across the product suite?

## Tasks

- [x] Existing: Travis CI build produces one (or more) (tested) Docker image(s)
- ~[ ] Existing: images are published with a latest tag on Docker Hub~ we may not need to push images if we run from source
- [x] New: create an `experiments` empty environment with a server
- [x] New: create buckets necessary to node.js Storage Service
- [x] New: a `storage-service/docker-compose.yml` configuration runs the node.js Storage Service on a server

Out of scope: automation of deployment
Out of scope: the equivalent of sample-configuration

/cc @petereast @diversemix

**Comment by giorgiosironi** [comment]
Demonstrated at http://shared-services-experiment.libero.pub:3000/

**Comment by giorgiosironi** [comment]
I assume this project needs to be configured with AWS credentials and a bucket name, even if we are not using the Configuration Service yet. How to do this? Only [`PG_HOST` is configured](https://github.com/libero/shared-services-experiment/blob/master/storage/docker-compose.yml#L18) along with a volume for (some kind of) storage.

**Comment by diversemix** [comment]
@petereast / @Cooryd ... this would be good to do ASAP, let me know if you would like help.

**Comment by petereast** [comment]
@Cooryd do you want to do this (as you know the s3 side of things best) or do you want me to have a crack?

**Comment by diversemix** [comment]
Looks like its all in env:
```
src/s3Repository.js
1:const AWS = require('aws-sdk');
6:    AWS_CREDENTIALS: {
7:      accessKeyId: process.env.AWS_ACCESS_KEY_ID || '',
8:      secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY || '',
9:      region: process.env.AWS_REGION || ''
```

**Comment by petereast** [comment]
Wow that was quick

**Comment by diversemix** [comment]
... then the rest comes from the configuration service, on a per namespace basis:
```
17:  return new AWS.S3({
25:  const s3 = getS3Instance(CONFIG[fData.namespace].AWS_CREDENTIALS);
39:  const s3 = getS3Instance(CONFIG[namespace].AWS_CREDENTIALS);
44:  const s3 = getS3Instance(CONFIG[namespace].AWS_CREDENTIALS);

```

**Comment by giorgiosironi** [comment]
> all in env

Yes, but `docker-compose.yml` needs to configure those so that they can be stored in the `.env` file for deploy.

**Comment by diversemix** [comment]
Let me put a PR in - so that we can pass them through the host to the container?

**Comment by giorgiosironi** [comment]
`.env` has been updated but not sure if the latest code is there, and/or the result has been tested. Leaving to @petereast to close when satisfied.
